version: '3.8'

services:
  postgres:
    image: postgres:13.21-alpine3.20
    container_name: postgresNest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456a}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
