version: '3.8'

services:
  postgres:
    image: postgres:16.13-alpine3.23
    container_name: postgresNest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432